version: '3.8'
services:
  server:
    image: uphschcich.azurecr.io.azurecr.io/seedo:main
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - ./.env
    tty: true
    stdin_open: true

networks:
  default:
    driver: bridge