# Override the standard production docker-compose.yml with local development settings
# https://docs.docker.com/compose/extends/#multiple-compose-files

version: '3.8'
services:
  server:
    image: seedo/server:latest
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: development
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    env_file:
      - ./.env
    # environment:
    #   - AUTH_DISABLED=true
    volumes:
      # - /server/node_modules
      - .:/app
    tty: true
    stdin_open: true
  
  # database:
  #   image: postgres:14.2
  #   ports: 
  #     - 5432:5432
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./db:/var/lib/postgresql/data
  #   tty: true
  #   stdin_open: true

networks:
  default:
    driver: bridge