version: '3.8'
services:
  server:
    image: uphschcich.azurecr.io/seedo-server:${IMAGE_TAG}
    build: 
      context: .
      dockerfile: ./server/Dockerfile
      target: production
    ports:
      - target: ${SERVER_PORT}
        published: ${SERVER_PORT}
        protocol: tcp
        mode: host
    tty: true
    stdin_open: true

  web:
    image: uphschcich.azurecr.io/seedo-web:${IMAGE_TAG}
    build: 
      context: .
      dockerfile: ./web/Dockerfile
      target: production
    ports:
      - target: ${WEB_PORT}
        published: ${WEB_PORT}
        protocol: tcp
        mode: host
    tty: true
    stdin_open: true
    depends_on:
      - server

networks:
  default:
    driver: bridge