version: '3.8'
services:
  server:
    env_file: ./.env
    build: 
      context: .
      dockerfile: ./server/Dockerfile
      target: development
    ports:
      - target: ${SERVER_PORT}
        published: ${SERVER_PORT}
        protocol: tcp
        mode: host
      - target: 9229
        published: 9229
        protocol: tcp
        mode: host
    volumes:
      - /app/server/node_modules
      - .:/app
    tty: true
    stdin_open: true

networks:
  default:
    driver: bridge