name: 'Build & Deploy'

on:
  release:
    types:
    - published
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: uphschcich.azurecr.io

jobs:
  build_function:
    name: Build Function
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@main
        with:
          submodules: recursive
          ssh-key: ${{ secrets.OBSERVABLES_DEPLOY_KEY }}


      - name: Extract Branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
               
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Log into container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/seedo-function-deploy
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long
            type=semver,pattern={{raw}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./function/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/seedo-function-deploy:latest
          cache-to: type=inline,mode=max

  deploy_dev:
    name: Deploy (Dev)
    needs: [ build_function ]
    runs-on: [ self-hosted, jump ]
    
    if: github.ref == 'refs/heads/dev'
    environment: development

    # NOTE: Docker must be installed on the runner
    container:
      image: uphschcich.azurecr.io/seedo-function-deploy:dev
      credentials:
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZURE_FUNCTION_APP_NAME: use2-chci-ch-seedo-dev-function

    steps:
      - name: Deploy function app
        shell: bash
        run: /root/deploy.sh

  deploy_prod:
    name: Deploy (Prod)
    needs: [ build_function ]
    runs-on: [ self-hosted, jump ]
    
    if: github.event.release.target_commitish == 'main' # only on main branch releases
    environment: production

    # NOTE: Docker must be installed on the runner
    container:
      image: uphschcich.azurecr.io/seedo-function-deploy:latest
      credentials:
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZURE_FUNCTION_APP_NAME: use2-chci-ch-seedo-prod-function

    steps:
      - name: Deploy function app
        shell: bash
        run: /root/deploy.sh
